NDLANO/article-converter

src/plugins/brightcovePlugin.js, src/plugins/imagePlugin.js
[I følge Johannes](https://trello.com/c/78mCbwBH/98-lisens-blir-ikke-med-n%C3%A5r-man-kopierer-referanse) skal lisens (inkludert "CC") og opprinnelse kopieres når man trykker på "kopier referanse")
=> copy license and origin #612

package.json, src/__tests__/__snapshots__/htmlTransformers-test.js.snap, src/htmlTransformers.js, src/utils/asideHelpers.js, yarn.lock
Fixes: https://trello.com/c/S58R2jXG/459-mye-luft-over-og-under-bilder-i-høyre
=> Don't wrap factbox or aside content in divs

src/__tests__/__snapshots__/replacer-test.js.snap, src/__tests__/replacer-test.js, src/plugins/audioPlugin.js
Resolves: https://github.com/NDLANO/Issues/issues/1005
=> Added support for mini player

package.json, src/__tests__/__snapshots__/htmlTransformers-test.js.snap, src/__tests__/__snapshots__/replacer-test.js.snap, src/__tests__/integration-tests/article1036/__snapshots__/article1036-test.js.snap, src/__tests__/integration-tests/article116/__snapshots__/article116-test.js.snap, src/__tests__/integration-tests/article2139/__snapshots__/article2139-test.js.snap, src/__tests__/integration-tests/article417/__snapshots__/article417-test.js.snap, src/locale/i18n.js, src/plugins/imagePlugin.js, yarn.lock
To test: 
- Run article-converter with ndla-frontend from branch "implement-new-clickToggle"
- Check that all clickToggles work (in authorByLine, FigureLicense etc)
=> Add correct id and props

package.json, src/__tests__/__snapshots__/replacer-test.js.snap, src/__tests__/integration-tests/article1036/__snapshots__/article1036-test.js.snap, src/__tests__/integration-tests/article2139/__snapshots__/article2139-test.js.snap, src/plugins/imagePlugin.js, yarn.lock
connects to https://github.com/NDLANO/Issues/issues/934
Testing: 
- Find article with image
- Attempt to download image from "Bruk bilde" and see that it downloads rather than opens in browser
=> #934: Adds query parameter to download image source

src/plugins/conceptPlugin.js
connected to NDLANO/Issues#1386
=> use authors from creators field when displaying concepts #1386

src/api/brightcove.js
Lager denne i påvente av avklaring fra Johannes.
=> support musikk

Dockerfile, run-article-converter.sh, src/config.js, src/swagger/swagger.yaml, src/swagger/swaggerDefinition.js
connected to NDLANO/Issues#1454
Kan ikke merges før nye auth0 setupet er på plass
=> read secrets from s3 #1454

src/plugins/imagePlugin.js, yarn.lock
connects to NDLANO/Issues#1522
Grunnen til at escapingen fantes tidligere var pga en bug i api-gateway som gjorde at url'en kunne bli escapet 2 ganger.
=> #1522: Don't escape url's from image-api as they are already escaped

src/plugins/contentLinkPlugin.js, src/plugins/index.js, src/routes.js
Connects to NDLANO/issues#1574
=> Add filters to internal url if present.

src/config.js
connects to NDLANO/Issues#1545
=> #1545: Handle env with underscore

src/routes.js
La til subject som mulig parameter på ett endepunkt til.
=> Add subject param to endpoint

src/api/conceptApi.js, src/plugins/conceptPlugin.js, src/utils/apiHelpers.js
=> Begrepstjeneste

src/api/conceptApi.js, src/plugins/conceptPlugin.js, src/utils/apiHelpers.js
Reverts NDLANO/article-converter#133
Vi har fått klarsignal på å deploye alt, men då må vi inntil videre hente forklaringer fra gammelt endepunkt.
=> Revert "Begrepstjeneste"

src/api/__tests__/__snapshots__/brightcove-test.js.snap, src/api/brightcove.js, src/plugins/pluginHelpers.js
=> Check type before returning copystring

src/api/brightcove.js
Tolke lisenser fra brightcove korrekt.
=> Add correct mapping.

src/__tests__/__snapshots__/replacer-test.js.snap, src/__tests__/integration-tests/article116/__snapshots__/article116-test.js.snap, src/__tests__/integration-tests/article2139/__snapshots__/article2139-test.js.snap, src/plugins/imagePlugin.js
Should fix article images medium size. (u-float-left / u-float-right)
i.e. last image on this page shouldnt be full; https://ndla.no/nn/subjects/subject:32/topic:1:165765/topic:1:165783/resource:1:97374
=> fix medium sized images

src/api/conceptApi.js, src/plugins/__tests__/__snapshots__/conceptPlugin-test.js.snap, src/plugins/__tests__/conceptPlugin-test.js, src/plugins/conceptPlugin.js, src/plugins/index.js, src/routes.js
NDLANO/Issues#2129
Legger til parameter for å vise draft-concepts.
=> Add possibilty to show draft concept

src/plugins/imagePlugin.js
=> Fix cropping for edge case

src/plugins/h5pPlugin.js
Legger tilbake h5p metadata. Trenger PR i graphql-api for å fungere.
=> Changed h5p metaData

src/fetchAndTransformArticle.js, src/htmlTransformers.js, src/plugins/relatedContentPlugin.js, src/utils/embedGroupHelpers.js
Fixes NDLANO/Issues#2253
Jeg gikk for å fjerne mutable staten helt og heller finne ut av indeksen fra elementet.
Det er sikkert slightly tregere, men syns lesbarheten øker. Kommenter gjerne på det :)
=> #2253: Fixes wrongly hidden related articles

src/plugins/__tests__/__snapshots__/contentLinkPlugin-test.js.snap, src/plugins/__tests__/__snapshots__/relatedContentPlugin-test.js.snap, src/plugins/__tests__/contentLinkPlugin-test.js, src/plugins/__tests__/relatedContentPlugin-test.js, src/plugins/contentLinkPlugin.js, src/plugins/relatedContentPlugin.js
Fixes NDLANO/Issues#2296
Vi bruker ikkje korrekt url for lenka artikler som finnes i samme faget.
=> Pick the correct path

src/config.js, src/plugins/conceptPlugin.js
Partially fixes: https://github.com/NDLANO/Issues/issues/2306
=> added concept metadata and iframe

package.json, yarn.lock
=> Bump packages to get bash

src/__tests__/integration-tests/article417/article9206-test.js, src/__tests__/replacer-test.js, src/plugins/conceptPlugin.js, src/replacer.js, src/transformers.js
Bruker eksisterende plugins for å rendre visuelt element for forklaring.
=> Shows visual element for concept.

package.json, src/plugins/codePlugin.js, yarn.lock
Fixes NDLANO/Issues#2387
Knappens lagrevisning avhenger av denne: https://github.com/NDLANO/frontend-packages/pull/737
[Artikkel med kodeblokker](test.ndla.no/article/22654)
=> #2387 Vise kopier kodeknapp

src/api/h5pApi.js, src/api/oembedProxyApi.js, src/plugins/externalPlugin.js, src/plugins/h5pPlugin.js, src/routes.js
NDLANO/Issues#2423
Legger til parameter som lar deg bruke h5p-preview-endepunkt fra ed. Ed skal oppdateres med bruk av parameter.
=> Use preview endpoint from ed

src/__tests__/integration-tests/article4835/__snapshots__/article4835-test.js.snap, src/utils/htmlTagHelpers.js
Viser inline pdf i ca A4 portrettmodus.
=> Increased height for inline pdf

src/plugins/__tests__/__snapshots__/contentLinkPlugin-test.js.snap, src/plugins/__tests__/contentLinkPlugin-test.js, src/plugins/contentLinkPlugin.js
Lenker fikk ikkje target blank på grunn av manglende $. Endra litt på koden for å unngå target=null.
=> Forcing blank target for links in oembed

src/__tests__/__snapshots__/htmlTransformers-test.js.snap, src/__tests__/htmlTransformers-test.js, src/htmlTransformers.js, src/routes.js
Legger på target blank for alle lenker som vises i oembed.
=> Adds target blank for all a in oembed

src/plugins/audioPlugin.js, src/plugins/brightcovePlugin.js, src/plugins/imagePlugin.js
Fjener mulighet for å laste ned fil dersom den har lisens Opphavsrett.
Deployer til test fra branch, og då skal denne ha innhold som ikkje kan lastes ned. https://test.ndla.no/subject:3/topic:8019e32d-5c05-46bc-99ad-32b0947fd944/resource:9c1feead-7749-421b-b1a7-5628e8272f8f
=> Fjerner nedlasting dersom copyright.

src/__tests__/integration-tests/article1036/__snapshots__/article1036-test.js.snap, src/__tests__/integration-tests/article116/__snapshots__/article116-test.js.snap, src/__tests__/integration-tests/article13349/__snapshots__/article13349-test.js.snap, src/__tests__/integration-tests/article2139/__snapshots__/article2139-test.js.snap, src/__tests__/integration-tests/article417/__snapshots__/article9206-test.js.snap, src/htmlTransformers.js, yarn.lock
Gjør det mulig å tabbe nedover ei side.
Fixes NDLANO/Issues#2579
=> Adding tabindex to h2 and h3

src/getEmbedMetaData.js, src/plugins/audioPlugin.js, src/plugins/brightcovePlugin.js, src/plugins/conceptPlugin.js, src/plugins/h5pPlugin.js, src/plugins/imagePlugin.js, src/plugins/index.js, src/replacer.js, src/transformers.js
Så ikke Gunnars kommentar på options-parameteren før jeg merga forrige pr, så skrur tilbake her for å heller bruke den globale options-parameteren i pluginsene i stedet for å sende til hver funksjon.
=> Skru tilbake options param

src/plugins/audioPlugin.js
Flytter uthenting av tekstversjon etter endring av api.
=> Moved manuscript to audio

.github/workflows/ci.yml, Dockerfile, package.json, src/api/brightcove.js, src/plugins/brightcovePlugin.js
fixes https://github.com/NDLANO/Issues/issues/2614
Removing the "&t=<seconds>" part from the videoid when fetching metadata from brightcove.
=> 2614 spesifisere start tid på brightcove videoer

.github/workflows/ci.yml, Dockerfile, package.json, src/plugins/brightcovePlugin.js
fixes https://github.com/NDLANO/Issues/issues/2615
=> Changed sort function to work correctly

src/config.js
Legger til mulihget for å spesifisere urler som miljøvariable.
=> Added possibility to specify all urls as params

src/__tests__/integration-tests/article270/__snapshots__/article270-test.js.snap, src/__tests__/integration-tests/article270/article270-test.js, src/fetchAndTransformArticle.js, src/plugins/conceptPlugin.js, src/routes.js, src/swagger/swaggerRoutes.js, src/transformers.js
Legger til parameter for visuelt element. 
Fikser også opp i swagger-parameter.
=> Added parameter to show visual element

src/routes.js, src/swagger/swaggerRoutes.js
Ikkje like hast, men kjekt å kunne sende parameter fra ed også.
=> Add param to post for use from ed.

src/__tests__/integration-tests/article1036/article1036-test.js, src/__tests__/integration-tests/article116/article116-test.js, src/__tests__/integration-tests/article13349/article13349-test.js, src/__tests__/integration-tests/article2139/article2139-test.js, src/__tests__/integration-tests/article270/article270-test.js, src/__tests__/integration-tests/article417/article9206-test.js, src/__tests__/integration-tests/article4835/article4835-test.js, src/api/articleApi.ts, src/fetchAndTransformArticle.ts, src/fetchEmbedMetaData.ts, src/interfaces.ts, src/plugins/conceptPlugin.tsx, src/plugins/relatedContentPlugin.tsx, src/routes.ts, src/transformers.ts
Adds handling of feidetoken when fetching article from article-api.
=> Add feideToken for fetching articles from article-api.

src/interfaces.ts, src/plugins/__tests__/__snapshots__/contentLinkPlugin-test.js.snap, src/plugins/__tests__/contentLinkPlugin-test.js, src/plugins/contentLinkPlugin.tsx, src/routes.ts, src/swagger/swaggerRoutes.ts
Legger på parameter for å kunne rendre urler som absolutte.
=> Add parameter to render absolute url

src/__tests__/integration-tests/article1036/article1036-test.js, src/__tests__/integration-tests/article116/article116-test.js, src/__tests__/integration-tests/article13349/article13349-test.js, src/__tests__/integration-tests/article2139/article2139-test.js, src/__tests__/integration-tests/article270/article270-test.js, src/__tests__/integration-tests/article417/article9206-test.js, src/__tests__/integration-tests/article4835/article4835-test.js, src/api/articleApi.ts, src/api/audioApi.ts, src/api/conceptApi.ts, src/api/imageApi.ts, src/api/taxonomyApi.ts, src/fetchAndTransformArticle.ts, src/fetchEmbedMetaData.ts, src/interfaces.ts, src/plugins/__tests__/__snapshots__/relatedContentPlugin-test.js.snap, src/plugins/__tests__/conceptPlugin-test.js, src/plugins/__tests__/contentLinkPlugin-test.js, src/plugins/__tests__/relatedContentPlugin-test.js, src/plugins/audioPlugin.tsx, src/plugins/brightcovePlugin.tsx, src/plugins/conceptPlugin.tsx, src/plugins/contentLinkPlugin.tsx, src/plugins/externalPlugin.tsx, src/plugins/h5pPlugin.tsx, src/plugins/imagePlugin.tsx, src/plugins/relatedContentPlugin.tsx, src/routes.ts, src/transformers.ts
Samler fleire params inn i ett objekt. Kom gjerne med tilbakemeldinger og forslag til endringer.
Plukker opp versionhash fra kallet og bruker det mot taksonomyApi.
=> Passthrough versionhash

package.json, yarn.lock
Bumper for å hente siste versjon av article-api types.
=> Bump to get revisionDate from article.

src/app.ts, src/swagger/swaggerDefinition.ts
Fixes NDLANO/Issues#3071
Kan testes om du har alt deploya lokalt
=> Makes it possible to call article-converter from swagger

src/__tests__/integration-tests/article116/__snapshots__/article116-test.js.snap, src/api/brightcove.ts, src/plugins/brightcovePlugin.tsx
Bruke name som fallback dersom description er tom.
=> Setting description to name if empty

package.json, src/api/audioApi.ts, src/api/imageApi.ts, src/plugins/audioPlugin.tsx, src/plugins/brightcovePlugin.tsx, src/plugins/iframePlugin.tsx, src/plugins/imagePlugin.tsx, yarn.lock
Påvirker:
- audio-api
- image-api
- article-api
Closes NDLANO/Issues#3139
=> Bruke genererte typer fra backend

src/__tests__/__snapshots__/getEmbedMetaData-test.js.snap, src/plugins/audioPlugin.tsx
NDLANO/Issues#3138
Avhenger av https://github.com/NDLANO/frontend-packages/pull/1269
Legger til podcast som metadata for artikkel.
=> Skiller mellom lydfil og podcast for artikkel

package.json, src/utils/conceptHelpers.tsx, src/utils/render.tsx, yarn.lock
Fixes NDLANO/Issues#3151
Legger til kildehenvisning og nedlasting av bilde i blokkforklaring.
Hvordan teste:
- Start opp lokalt med graphql og ndla-frontend på master
- Åpne http://localhost:3000/article/31483
- Trykk inn på blokkforklaring og deretter inn på bildelisens. Se at knapper for kildehenvisning og nedlasting finnes og at det fungerer.
=> 3151 concept image download

src/plugins/audioPlugin.tsx
Fixes NDLANO/Issues#3324
Legger til url til podkastside på episode.
=> Legger til lenke til podkast-serie fra episode.

Dockerfile, src/config.ts, src/swagger/swaggerDefinition.ts
NDLANO/Issues#3340
Skriver litt om i forbindelse med å bytte ut support-epostadresse.
Fjerner også pm2.
Test gjerne lokalt og sjekk at alt funker. Også at du kan bytte ut config i swagger doc.
=> 3340 add config params for swagger

src/plugins/__tests__/contentLinkPlugin-test.js, src/plugins/contentLinkPlugin.tsx
Relates to https://github.com/NDLANO/backend/pull/156
Denne er bakoverkompatibel :^)
=> Support content-link children text

package.json, yarn.lock
Fixes https://github.com/NDLANO/article-converter/security/dependabot/3
Fixes https://github.com/NDLANO/article-converter/security/dependabot/33
Fixes https://github.com/NDLANO/article-converter/security/dependabot/34
Fixes https://github.com/NDLANO/article-converter/security/dependabot/2
Fixes https://github.com/NDLANO/article-converter/security/dependabot/12
https://github.com/NDLANO/article-converter/security/dependabot/6
=> Bump babel

package.json, yarn.lock
Fixes https://github.com/NDLANO/article-converter/security/dependabot/13
=> Bump swagger
