src/__tests__/__snapshots__/replacer-test.js.snap
src/__tests__/replacer-test.js
src/plugins/__tests__/__snapshots__/contentLinkPlugin-test.js.snap
src/plugins/__tests__/contentLinkPlugin-test.js
src/plugins/contentLinkPlugin.js

contentLinkPlugin now has a fetchResource function that fetches
taxonomyPath for the given article. Falls back to old path without
taxonomy if not found.

#879: contentLinkPlugin now fetches taxonomy

---

src/plugins/__tests__/__snapshots__/relatedContentPlugin-test.js.snap
src/plugins/__tests__/relatedContentPlugin-test.js
src/plugins/relatedContentPlugin.js

If article can be found in article-api, but not in taxonomy, the related
content are still rendered, but with a simple /article/\<id\> url rather
than the full context url.

#879: Related content url now falls back to url without taxonomy

---

src/plugins/brightcovePlugin.js

Prevents article-converter to fail when embedded brightcove video misses parameter.
Ref: https://ndla.no/subjects/subject:19/topic:1:195877/topic:1:6738?disableSSR=true

Check value before use

---

package.json
src/plugins/codePlugin.js
yarn.lock

Fordi vi la til lagring av html-encoda kode må vi decode ved visning.
Test: Legg til htmlkode i artikkel i ed og klikk på forhåndsvis. Vil funke når eg har deploya article-converter til test fra branch.

Add decoding of code

---

src/__tests__/integration-tests/article270/article270-test.js
src/__tests__/integration-tests/article417/article9206-test.js
src/plugins/__tests__/__snapshots__/contentLinkPlugin-test.js.snap
src/plugins/__tests__/contentLinkPlugin-test.js
src/plugins/h5pPlugin.js

Added nock to test to avoid ugly log.
Replace deprecated endpoints in taxonomy.
NDLANO/Issues#2338
Sender nytt locale-parameter til h5p for å være sikker på at h5p vises med riktig språkdrakt.

Add locale to oembed-request for h5p.

---

package.json
src/plugins/audioPlugin.js
src/plugins/conceptPlugin.js
src/plugins/imagePlugin.js
yarn.lock

Fikser krasj oppstått i prod der en forklaring hadde et bilde som blei sletta som visuelt element.

Extra check before rendering metadata

---

src/__tests__/integration-tests/article13349/__snapshots__/article13349-test.js.snap
src/__tests__/integration-tests/article4835/__snapshots__/article4835-test.js.snap
src/__tests__/integration-tests/article4835/article4835.js
src/htmlTransformers.js
src/utils/htmlTagHelpers.js

Fixes NDLANO/Issues#2410
Hører sammen med https://github.com/NDLANO/editorial-frontend/pull/883
Fil-embeds er oppdatert med en attributt "data-display". Dersom denne er satt til "block" og filtypen er "pdf" så skal PDFen vises i en iframe.
How to test:
1. yarn start
2. Editorial yarn start-with-local-converter (branch 2410-inline-visning-av-pdf-i-artikkel)
3. Åpne en artikkel, feks http://localhost:3000/preview/22741/nb 
4. Marker ingen, en eller flere PDF-filer og sjekk at de markerte pdf'ene vises i forhåndsvisning av artikkel.

2410 inline visning av pdf i artikkel

---

src/__tests__/__snapshots__/replacer-test.js.snap
src/plugins/audioPlugin.js

Viser podcastfelt i audio. Gjør audio til størrelse full for at den skal bli like brei som bilder og i ed.
Test:
Må kjøres lokalt sammen med ed som må kjøres med start-with-local-converter.
http://localhost:3000/preview/30642/nb skal vises med podcastnformasjon.

Adding podcast-fields to audioPlugin

---

src/api/__tests__/__snapshots__/oembedProxyApi-test.js.snap
src/api/__tests__/brightcove-test.js
src/api/__tests__/oembedProxyApi-test.js
src/api/oembedProxyApi.js

Yotube-adresser som er lagra med http vises greit i ed, men ikkje i frontend. Det er fordi oembed-tjenesten til youtube har slutta å godta http-adresser.

Converts youtube http-adresses to https

---

src/app.js
src/fetchEmbedMetaData.js
src/routes.js
src/swagger/swagger.yaml
src/swagger/swaggerRoutes.js
src/transformers.js

Legger til et nytt endepunkt: `/article-converter/json/:lang/meta-data` for å hente h5p og brightcove metadata

License endpoint

---

src/api/__tests__/__snapshots__/brightcove-test.js.snap
src/api/__tests__/brightcove-test.js
src/plugins/__tests__/__snapshots__/pluginHelpers-test.js.snap
src/plugins/__tests__/pluginHelpers-test.js
src/plugins/pluginHelpers.js

Lisensinformasjon i brightcove er registrert manuellt og dermed sårbart for skrivefeil. Eksisterende kode knekker dersom en video har fått info: `Ophavsmann: Fornavn Etternavn`. Endringa tar høgde for at type bearbeider er tom. Det er ikkje ideellt at teksten då vil bli `: Fornavn Etternavn` men det er et signal om at noko ikkje er som det skal være.

I tilfelle feil i type fra brightcove

---

src/plugins/audioPlugin.js

La inn et eksplisitt kall til `changeLanguage`. Det viste seg at i18next-språket var satt til 'nn', men `t`-funksjonen tok i bruk 'nb' som språk. Litt usikker på hvorfor dette skjer akkurat her, men å kalle på `changeLanguage` eksplisitt inne i audioPlugin sin render-funksjon ser ut til å fikse det.

Added more explicit language setting for audio plugin

---

src/fetchAndTransformArticle.js

Grensetilfelle, men ressursartikler som kun har en embed bør vises uansett om den ikkje har tekst.
Test:
* Kjør branch lokalt med yarn start
* Kjør ed lokalt med `yarn start-with-local-converter`
* Forhåndsvis en ressurs som kun har embeds i seg.

Always return content for standard

---

src/api/taxonomyApi.js

Lenke til artikkel uten kontekst vises fordi det ligger en gammel topic i basen som ikkje har path. Slike topics trengs for at redirect skal fungere.
i prod:  https://ndla.no/subject:1:058bdbdb-aa5a-4a29-88fb-45e664999417/topic:1:0c9ce0dc-3863-4e03-a2df-a1480a4e929c/topic:1:94ceef85-9325-4c6b-82fb-2434ce5e2817/resource:e3358cde-7cc3-48ca-b2a9-65a64910bd53
Test
* http://localhost:3100/article-converter/html/nb/28046 skal ha en taksonomiurl under lenka Verktøykassa.

Filtering old topics with no path.

---

src/plugins/brightcovePlugin.tsx

Fixes NDLANO/Issues#2688
Testes sammen med https://github.com/NDLANO/editorial-frontend/pull/1307
Sjekker om link text er et tall før det brukes.
Test:
* Sjekk visning av artikkel 31334, der kun den første skal ha knapp for å bytte til synstolket.

Checking if is numeric before linking video

---

src/__tests__/__snapshots__/htmlTransformers-test.js.snap
src/__tests__/htmlTransformers-test.js
src/htmlTransformers.ts

Fixes NDLANO/Issues#2971
Sjekker at ikkje h2 konverteres inni details, aside eller bodybox. Kunne sikkert vore gjort meir elegant, men det fungerer.
Test
* Kjør lokalt med ed og sjekk at du ikkje får ankerknapp i denne artikkelen: http://localhost:3000/preview/31368/nb

Filters out h2-anchors also in textboxes.

---

package.json
src/__tests__/__snapshots__/getEmbedMetaData-test.js.snap
src/__tests__/__snapshots__/replacer-test.js.snap
src/__tests__/integration-tests/article1036/__snapshots__/article1036-test.js.snap
src/__tests__/integration-tests/article116/__snapshots__/article116-test.js.snap
src/__tests__/integration-tests/article13349/__snapshots__/article13349-test.js.snap
src/__tests__/integration-tests/article2139/__snapshots__/article2139-test.js.snap
src/__tests__/integration-tests/article270/__snapshots__/article270-test.js.snap
src/__tests__/integration-tests/article417/__snapshots__/article9206-test.js.snap
src/__tests__/integration-tests/article4835/__snapshots__/article4835-test.js.snap
src/fetchAndTransformArticle.ts
src/plugins/audioPlugin.tsx
src/plugins/imagePlugin.tsx
yarn.lock

Testes lokalt med graphql og ndla-frontend.
Følgende er nytt i tekst for kopiering under "regler for bruk" og i figurer i artikkelen:
- Både opphavere og rettighetshavere listes opp dersom begge deler finnes.
- Personer/organisasjoner skilles med komma
Spesifikt for kildehenvisning til artikkel (se "regler for bruk" i bunnen av en artikkel):
- kort url til artikkel brukes. Altså /articles/:id og nå vises også ndla-domene (feks http://test.ndla.no) i starten av url.

Hotfix: Feilrettinger på apa-referanser

---

src/interfaces.ts
src/plugins/imagePlugin.tsx
src/routes.ts

Viser alt-tekst for bilder dersom article-converter kalles fra ed med en gitt parameter.
Test:
* Kjøres sammen med tilhørende PR i ed
* Forhåndsvisning og språksammenligning skal ha med alt-tekst.

Add alt-text to article if previewAlt is specified.

---

package.json
src/plugins/audioPlugin.tsx
src/plugins/imagePlugin.tsx
yarn.lock

Dersom et bilde har copyright skal ikke knapp for kopiering av kildehenvisning vises. Denne PRen fikser dette for figurerer som vises underveis i en artikkel.
Hvordan teste:
1. Spinn opp ndla-frontend med lokal graphql og article-converter.
2. Åpne en artikkel som innholder et bilde med COPYRIGHT som lisens.
3. Trykk på regler for bruk og sjekk at bildet ikke har knapp for verken nedlasting eller kildehenvisning

Hide copytext on copyright

---

src/__tests__/__snapshots__/htmlTransformers-test.js.snap
src/__tests__/integration-tests/article1036/__snapshots__/article1036-test.js.snap
src/__tests__/integration-tests/article116/__snapshots__/article116-test.js.snap
src/__tests__/integration-tests/article2139/__snapshots__/article2139-test.js.snap
src/htmlTransformers.ts

Relatert til https://github.com/NDLANO/ndla-frontend/pull/951
Legger til attributten `data-from-article-converter`, som lar oss unngå å utføre spesifikke handlinger på ting som kommer fra article-converter.

Add custom attribute for converter rendered portals

---

src/app.ts

NDLANO/Issues#3070
Express defaulter til 100K som maks størrelse, men det er i noen tilfeller for lite. Øker denne til 2mb her og i api-gateway for å ha litt å gå på.
Kan testes med å forhåndsvise denne sida om du kjører ed med lokal converter: http://localhost:3000/nn/preview/31431/nb
Uten denne endringa vil du få tom side og 413 feil fra converter.

Increase body size

---

src/htmlTransformers.ts

Fikser problemet på http://localhost:3000/nn/subject:1:3b74fa5e-aeb8-4bc3-b771-fb2c0230b5f4/topic:1:ad12f9f6-2770-4fa6-a710-bbb7cd669651/topic:1:06ae6019-ae22-4964-ad65-ea8ef03d7ba1/resource:1:122989
Kan testes ved å starte opp lokal graphql, article-converter og ndla-frontend, for deretter å gå inn på linken over. Hvis det ikke krasjer funker det.

Moves moveReactPortals further down so that it runs after tables have been transformed

---

src/getEmbedMetaData.ts
src/interfaces.ts
src/plugins/iframePlugin.tsx

Closes https://github.com/NDLANO/Issues/issues/3158
Finner feilen ved å gå for eksempel her: https://test.ndla.no/nb/article/31044, og velge "regler for bruk". Da vil man ikke få opp regler for bruk av bilder som ligger i en iframe.

Make image info from iframes visible in cite or use

---

src/plugins/h5pPlugin.tsx

Same as https://github.com/NDLANO/editorial-frontend/pull/1565
Sends more language-codes to h5p-service.

More language codes to hp5

---

src/plugins/conceptPlugin.tsx

Fixes NDLANO/Issues#3304
Dersom forklaring ikkje finnes gir det ingen meining i å vise en dialog med feilmelding. Bedre å berre vise teksten fra embedden slik at det ikkje ser ut som om det var en forklaring der.

If no concept found, just display embed text to avoid empty modal

---

package.json
src/plugins/conceptPlugin.tsx

Skriver om markdown i inline forklaring til å bruke `parse` fra `html-react-parser` i stedet for dangerouslyInsertHTML. 
Hvordan teste:
1. Kjør opp med lokal graphql og ndla-frontend
2. Åpne /articles/31466
3. Klikk på inline forklaring øverst
4. Se at markdown i innhold og i lenke på bunnen av modalen rendres korrekt.
<details>
<summary>
bilde
</summary>
</details>
Har rigget klar denne artikkelen for dette: https://test.ndla.no/article/31466.

Use react-html-parser for markdown
